import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GALLERY_DIR = path.join(ROOT_DIR, "public", "gallery");
const OUTPUT_FILE = path.join(ROOT_DIR, "src", "data", "gallery.generated.ts");

const SUPPORTED_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const YEAR_FOLDER_PATTERN = /^\d{4}$/;

function isSupportedImage(fileName) {
  return SUPPORTED_EXTENSIONS.has(path.extname(fileName).toLowerCase());
}

function buildImageUrl(yearName, eventName, fileName) {
  return `/gallery/${yearName}/${eventName}/${fileName}`;
}

function scanGallery() {
  if (!fs.existsSync(GALLERY_DIR)) {
    return [];
  }

  const yearNames = fs
    .readdirSync(GALLERY_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => YEAR_FOLDER_PATTERN.test(name))
    .sort((a, b) => Number(b) - Number(a));

  const galleryEvents = [];

  for (const yearName of yearNames) {
    const yearDir = path.join(GALLERY_DIR, yearName);
    const eventNames = fs
      .readdirSync(yearDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort((a, b) => a.localeCompare(b));

    for (const eventName of eventNames) {
      const eventDir = path.join(yearDir, eventName);
      const images = fs
        .readdirSync(eventDir)
        .filter(isSupportedImage)
        .sort((a, b) => a.localeCompare(b))
        .map((fileName) => buildImageUrl(yearName, eventName, fileName));

      if (images.length === 0) {
        continue;
      }

      galleryEvents.push({
        year: Number(yearName),
        event: eventName,
        cover: images[0],
        imageCount: images.length,
        images,
      });
    }
  }

  return galleryEvents;
}

function renderGeneratedFile(galleryEvents) {
  const lines = [
    "// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.",
    "// Regenerated by scripts/generate-gallery.js before `npm run dev` and `npm run build`.",
    "",
    "export interface GalleryEvent {",
    "  year: number;",
    "  event: string;",
    "  cover: string;",
    "  imageCount: number;",
    "  images: string[];",
    "}",
    "",
    "export const galleryEvents: GalleryEvent[] = " + JSON.stringify(galleryEvents, null, 2) + ";",
    "",
  ];
  return lines.join("\n");
}

function generate() {
  const galleryEvents = scanGallery();
  const content = renderGeneratedFile(galleryEvents);

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");

  const imageCount = galleryEvents.reduce((sum, event) => sum + event.imageCount, 0);
  console.log(`[gallery] Generated ${galleryEvents.length} event(s) with ${imageCount} image(s).`);
}

generate();
