// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Regenerated by scripts/generate-gallery.js before `npm run dev` and `npm run build`.

export interface GalleryEvent {
  year: number;
  event: string;
  cover: string;
  imageCount: number;
  images: string[];
}

export const galleryEvents: GalleryEvent[] = [
  {
    "year": 2026,
    "event": "hackathon",
    "cover": "/gallery/2026/hackathon/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/hackathon/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2026,
    "event": "ignite",
    "cover": "/gallery/2026/ignite/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/ignite/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2026,
    "event": "illuminate",
    "cover": "/gallery/2026/illuminate/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/illuminate/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2026,
    "event": "sparkathon",
    "cover": "/gallery/2026/sparkathon/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/sparkathon/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2025,
    "event": "Group discussion",
    "cover": "/gallery/2025/Group discussion/grpdis1.jpg",
    "imageCount": 2,
    "images": [
      "/gallery/2025/Group discussion/grpdis1.jpg",
      "/gallery/2025/Group discussion/grpdis2.JPG"
    ]
  },
  {
    "year": 2025,
    "event": "Illuminate",
    "cover": "/gallery/2025/Illuminate/illu1.jpeg",
    "imageCount": 8,
    "images": [
      "/gallery/2025/Illuminate/illu1.jpeg",
      "/gallery/2025/Illuminate/illu2.jpeg",
      "/gallery/2025/Illuminate/illu3.jpeg",
      "/gallery/2025/Illuminate/illu4.jpeg",
      "/gallery/2025/Illuminate/illu5.jpeg",
      "/gallery/2025/Illuminate/illu6.jpeg",
      "/gallery/2025/Illuminate/illu7.jpeg",
      "/gallery/2025/Illuminate/illu8.jpeg"
    ]
  },
  {
    "year": 2025,
    "event": "LinkedIn Presentation",
    "cover": "/gallery/2025/LinkedIn Presentation/lnkdinpress1.JPG",
    "imageCount": 5,
    "images": [
      "/gallery/2025/LinkedIn Presentation/lnkdinpress1.JPG",
      "/gallery/2025/LinkedIn Presentation/lnkdinpress2.JPG",
      "/gallery/2025/LinkedIn Presentation/lnkdinpress3.JPG",
      "/gallery/2025/LinkedIn Presentation/lnkdinpress4.png",
      "/gallery/2025/LinkedIn Presentation/lnkdinpress5.png"
    ]
  },
  {
    "year": 2025,
    "event": "Pitchnova",
    "cover": "/gallery/2025/Pitchnova/pitch1.jpeg",
    "imageCount": 9,
    "images": [
      "/gallery/2025/Pitchnova/pitch1.jpeg",
      "/gallery/2025/Pitchnova/pitch2.jpeg",
      "/gallery/2025/Pitchnova/pitch3.jpeg",
      "/gallery/2025/Pitchnova/pitch4.jpeg",
      "/gallery/2025/Pitchnova/pitch5.jpeg",
      "/gallery/2025/Pitchnova/pitch6.jpeg",
      "/gallery/2025/Pitchnova/pitch7.jpeg",
      "/gallery/2025/Pitchnova/pitch8.jpeg",
      "/gallery/2025/Pitchnova/pitch9.jpeg"
    ]
  },
  {
    "year": 2025,
    "event": "Quiznova",
    "cover": "/gallery/2025/Quiznova/quizn1.jpeg",
    "imageCount": 5,
    "images": [
      "/gallery/2025/Quiznova/quizn1.jpeg",
      "/gallery/2025/Quiznova/quizn2.jpeg",
      "/gallery/2025/Quiznova/quizn3.jpeg",
      "/gallery/2025/Quiznova/quizn4.jpeg",
      "/gallery/2025/Quiznova/quizn5.jpeg"
    ]
  },
  {
    "year": 2025,
    "event": "Seminar",
    "cover": "/gallery/2025/Seminar/semin1.jpeg",
    "imageCount": 4,
    "images": [
      "/gallery/2025/Seminar/semin1.jpeg",
      "/gallery/2025/Seminar/semin2.jpeg",
      "/gallery/2025/Seminar/semin3.jpeg",
      "/gallery/2025/Seminar/semin4.jpeg"
    ]
  },
  {
    "year": 2025,
    "event": "Team",
    "cover": "/gallery/2025/Team/group photo.png",
    "imageCount": 1,
    "images": [
      "/gallery/2025/Team/group photo.png"
    ]
  }
];
