// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Regenerated by scripts/generate-gallery.js before `npm run dev` and `npm run build`.

export interface GalleryEvent {
  year: number;
  event: string;
  cover: string;
  imageCount: number;
  images: string[];
}

export const galleryEvents: GalleryEvent[] = [
  {
    "year": 2026,
    "event": "hackathon",
    "cover": "/gallery/2026/hackathon/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/hackathon/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2026,
    "event": "ignite",
    "cover": "/gallery/2026/ignite/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/ignite/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2026,
    "event": "illuminate",
    "cover": "/gallery/2026/illuminate/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/illuminate/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2026,
    "event": "sparkathon",
    "cover": "/gallery/2026/sparkathon/RobloxScreenShot20260515_170041038.png",
    "imageCount": 1,
    "images": [
      "/gallery/2026/sparkathon/RobloxScreenShot20260515_170041038.png"
    ]
  },
  {
    "year": 2025,
    "event": "out of the box",
    "cover": "/gallery/2025/out of the box/RobloxScreenShot20260515_170452377.png",
    "imageCount": 1,
    "images": [
      "/gallery/2025/out of the box/RobloxScreenShot20260515_170452377.png"
    ]
  },
  {
    "year": 2025,
    "event": "pitchnova",
    "cover": "/gallery/2025/pitchnova/RobloxScreenShot20260515_170452377.png",
    "imageCount": 1,
    "images": [
      "/gallery/2025/pitchnova/RobloxScreenShot20260515_170452377.png"
    ]
  },
  {
    "year": 2025,
    "event": "prompt o thon",
    "cover": "/gallery/2025/prompt o thon/RobloxScreenShot20260515_170452377.png",
    "imageCount": 1,
    "images": [
      "/gallery/2025/prompt o thon/RobloxScreenShot20260515_170452377.png"
    ]
  },
  {
    "year": 2025,
    "event": "reverse pitch",
    "cover": "/gallery/2025/reverse pitch/RobloxScreenShot20260515_170452377.png",
    "imageCount": 1,
    "images": [
      "/gallery/2025/reverse pitch/RobloxScreenShot20260515_170452377.png"
    ]
  }
];
